No resolve or reject in the promise constructor the .then is not ran.
Same as the `.catch`,  `.finally`.

why?
These methods are invoked by either a `resolve` or a `reject`.

